name: pythole
channels:
  - https://conda.anaconda.org/conda-forge
dependencies:
  # general
  - python =3.11
  - pip  # python packaging tool

  # automatic linters / checkers / tests / CI
  - pre-commit  # runs pre commit/push hooks
  - black  # code formatter
  - flake8  # pep8 linter
  - autoflake  # remove unused imports / variables

  # non automatic
  - mypy  # type checker
  - pylint  # heavyweight linter
  - coverage  # code coverage
  - pytest  # python testing framework
  - cruft # keep up with cookiecutter updates

  # cli
  - typer  # handy cli library with support for type checking
  - rich  # colorful styles and terminal outputs

  # docs
  - sphinx  # documentation framework, uses restructured text (.rst)

  # # numerical
  - numpy  # multidimensional array support
  - h5py  # HDF5 backend
