import pandas as pd

df = pd.read_csv("grid-search.csv", sep=" ")
df = pd.read_csv("grid-search-no-outliers.csv", sep=" ")
print("No Correction")
print(df.iloc[0])
print()
print("Best MRAD")
print(df.iloc[df["mrad"].argmin()])
print()
print("Best MAD:")
print(df.iloc[df["mad[kcal/mol]"].argmin()])
print()
print("Best RMSE")
print(df.iloc[df["rmse[kcal/mol]"].argmin()])
print()
print("Paper model: epsilon=2 and no damp")
print(df.iloc[5])
print()
print("Thole with damp=0.3")
print(df.iloc[31])
print()
